### PR TITLE
Updates from testing

### PR DESCRIPTION
**Pull request by jacobemery**
Added some updates from my testing.

### CODE REVIEW

**Review by AmadeusPodvratnik — CHANGES_REQUESTED** [review]
Hi @jacobemery , for roles/ssh_cp_keys_jumphost/tasks/main.yaml pls revert the change because env.jumhost.path_to_keypair is the path on the jumphost and not on the workstation (this matches the documentation).

For playbooks/5_setup_bastion.yaml you changed the hosts from localhost to jumphost which should stay to localhost because you copy the local id file to bastion. 
- First copy: Copy ID file to jumphost
- Second copy: Copy ID file from jumphost to bastion
- Third copy: Copy ID file from localhost/workstation to bastion

You changed in roles/create_bastion/tasks/main.yaml
--location http://{{ env.ftp.ip }}/{{ env.ftp.iso_mount_dir }} \ 
Which is not clear why you move the http location of the iso to KVM IP.  If you would like to leverage the KVM host, it would be better to use a Flag (I'm just testing) like access_type: HTTP for the ftp section.

**Comment by jacobemery** [comment]
@AmadeusPodvratnik Ah, yes very good points. After our conversation yesterday about the ssh config I understood better than when I made these commits. And with KVM, you're right there too. I'll fix things up here and commit again when I can.
Everything else look ok to you?

**Comment by AmadeusPodvratnik** [comment]
@jacobemery Yes, the rest looks good so far :-). Thx!!

**Review by AmadeusPodvratnik — APPROVED** [review]

**Comment by jacobemery** [comment]
@AmadeusPodvratnik I went through a full, clean run-through of NAT using these patches, and made sure that macvtap still works too with a full run-through. Let me know what you think! Would love to merge this and then your PR into main today.

**Review by AmadeusPodvratnik — APPROVED** [review]

**Review by AmadeusPodvratnik — APPROVED** [review]
Thank you ...

**Review by AmadeusPodvratnik — APPROVED** [review]

**Review by AmadeusPodvratnik — APPROVED** [review]

**Review by AmadeusPodvratnik — APPROVED** [review]

**Review by AmadeusPodvratnik — APPROVED** [review]

**Pull request merged**
